version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Entered the install phase...
      
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Build started on `date`
      
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean package -DskipTests
      
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      
artifacts:
  files:
    - target/timeblock-service-0.0.1-SNAPSHOT.jar
    - Procfile
  name: timeblock-service-$(date +%Y-%m-%d) 